import type { Artist, ArtistSubmission } from "@/types"

export const mockArtists: Artist[] = [
    {
        id: 1,
        name: "Sarah Johnson",
        category: "Singer",
        location: "New York, NY",
        rating: 4.9,
        reviews: 127,
        priceRange: "$500-1000",
        image: "/artist/sarah.png?height=300&width=300",
        specialties: ["Jazz", "Pop", "Soul", "R&B"],
        bio: "Professional vocalist with over 10 years of experience performing at weddings, corporate events, and private parties. Known for her soulful voice and ability to connect with audiences.",
        experience: "10+ years",
    },
    {
        id: 2,
        name: "Michael Chen",
        category: "DJ",
        location: "Los Angeles, CA",
        rating: 4.8,
        reviews: 89,
        priceRange: "$300-800",
        image: "/artist/michael.png?height=300&width=300",
        specialties: ["Electronic", "Hip-Hop", "House", "Top 40"],
        bio: "Award-winning DJ specializing in electronic music and crowd engagement. Perfect for nightclubs, festivals, and high-energy events.",
        experience: "8+ years",
    },
    {
        id: 3,
        name: "Elena Rodriguez",
        category: "Dancer",
        location: "Miami, FL",
        rating: 5.0,
        reviews: 156,
        priceRange: "$400-900",
        image: "/artist/elena.png?height=300&width=300",
        specialties: ["Latin", "Contemporary", "Ballet", "Salsa"],
        bio: "Classically trained dancer with expertise in multiple dance styles. Available for performances, choreography, and dance instruction.",
        experience: "12+ years",
    },
    {
        id: 4,
        name: "David Thompson",
        category: "Speaker",
        location: "Chicago, IL",
        rating: 4.7,
        reviews: 203,
        priceRange: "$1000-2000",
        image: "/artist/david.png?height=300&width=300",
        specialties: ["Motivational", "Business", "Leadership", "Innovation"],
        bio: "Keynote speaker and business consultant with a track record of inspiring audiences at corporate events and conferences worldwide.",
        experience: "15+ years",
    },
    {
        id: 5,
        name: "Jessica Park",
        category: "Singer",
        location: "Nashville, TN",
        rating: 4.6,
        reviews: 94,
        priceRange: "$400-800",
        image: "/artist/jessica.png?height=300&width=300",
        specialties: ["Country", "Folk", "Acoustic", "Indie"],
        bio: "Singer-songwriter with a passion for storytelling through music. Perfect for intimate venues and acoustic performances.",
        experience: "7+ years",
    },
    {
        id: 6,
        name: "Marcus Williams",
        category: "DJ",
        location: "Atlanta, GA",
        rating: 4.9,
        reviews: 178,
        priceRange: "$500-1200",
        image: "/artist/marcus.png?height=300&width=300",
        specialties: ["Hip-Hop", "R&B", "Trap", "Old School"],
        bio: "Professional DJ with deep roots in hip-hop culture. Specializes in creating unforgettable experiences for weddings and parties.",
        experience: "11+ years",
    },
    {
        id: 7,
        name: "Anna Kowalski",
        category: "Dancer",
        location: "Boston, MA",
        rating: 4.8,
        reviews: 112,
        priceRange: "$350-700",
        image: "/artist/anna.png?height=300&width=300",
        specialties: ["Modern", "Jazz", "Hip-Hop", "Commercial"],
        bio: "Versatile dancer and choreographer with experience in music videos, live performances, and dance competitions.",
        experience: "9+ years",
    },
    {
        id: 8,
        name: "Robert Kim",
        category: "Speaker",
        location: "San Francisco, CA",
        rating: 4.9,
        reviews: 267,
        priceRange: "$1500-3000",
        image: "/artist/robert.png?height=300&width=300",
        specialties: ["Technology", "Entrepreneurship", "Innovation", "Startups"],
        bio: "Tech entrepreneur and thought leader who has spoken at major conferences including TED, SXSW, and Web Summit.",
        experience: "20+ years",
    },
]

export const mockArtistSubmissions: ArtistSubmission[] = [
    {
        id: 1,
        name: "Alex Rivera",
        email: "alex.rivera@email.com",
        category: "Singer",
        location: "Austin, TX",
        feeRange: "$500-1000",
        status: "pending",
        submittedDate: "2025-01-15",
        image: "/dashboard/alex.png?height=40&width=40",
    },
    {
        id: 2,
        name: "Maya Patel",
        email: "maya.patel@email.com",
        category: "Dancer",
        location: "Seattle, WA",
        feeRange: "$400-800",
        status: "approved",
        submittedDate: "2025-01-12",
        image: "/dashboard/maya.png?height=40&width=40",
    },
    {
        id: 3,
        name: "James Wilson",
        email: "james.wilson@email.com",
        category: "DJ",
        location: "Denver, CO",
        feeRange: "$300-600",
        status: "approved",
        submittedDate: "2025-01-10",
        image: "/dashboard/james.png?height=40&width=40",
    },
    {
        id: 4,
        name: "Sophie Laurent",
        email: "sophie.laurent@email.com",
        category: "Speaker",
        location: "Portland, OR",
        feeRange: "$1000-2000",
        status: "rejected",
        submittedDate: "2025-01-08",
        image: "/dashboard/sophie.png?height=40&width=40",
    },
    {
        id: 5,
        name: "Carlos Mendez",
        email: "carlos.mendez@email.com",
        category: "Singer",
        location: "Phoenix, AZ",
        feeRange: "$400-700",
        status: "pending",
        submittedDate: "2025-01-14",
        image: "/dashboard/carlos.png?height=40&width=40",
    },
]
